IKTU_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from product.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('product/', include('product.urls', namespace='product')),
    path('user/', include('user.urls', namespace='user')),
    path('basketadd/<int:product_id>/', include('product.urls', namespace='basketadd')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user.views import log, reg, prof

app_name = 'user'

urlpatterns = [
    path('login/', log, name='log'),
    path('reg/', reg, name='reg'),
    path('prof/', prof, name='prof'),

]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    img = models.ImageField(upload_to='user_img', blank=True)

user/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from user.models import User
from django import forms


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Пайдаланушы атты енгізіңіз'}))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Құпиясөзді енгізіңіз'}))

    class Meta:
        model = User
        fields = ('username', 'password')

    def __int__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class RegForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control py-4', 'placeholders': 'Атыңызды енгізіңіз'}))
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control py-4', 'placeholders': 'Фамилияңызды енгізіңіз'}))
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control py-4', 'placeholders': 'Пайдаланушы атты енгізіңіз'}))
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control py-4', 'placeholders': 'Эл.почтаңызды енгізіңіз'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control py-4', 'placeholders': 'Құпиясөзді енгізіңіз'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control py-4', 'placeholders': 'Қайта жазыңыз'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def __int__(self, *args, **kwargs):
        super(RegForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class ProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': False}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': False}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'img')

    def __int__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['img'].widget.attrs['class'] = 'custom-file-input'

user/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required

from user.forms import LoginForm, RegForm, ProfileForm
from product.models import Basket


def log(request):
    if request.method == 'POST':
        frm = LoginForm(data=request.POST)
        if frm.is_valid():
            usern = request.POST['username']
            passwd = request.POST['password']
            userr = auth.authenticate(username=usern, password=passwd)
            if userr and userr.is_active:
                auth.login(request, userr)
                return HttpResponseRedirect(reverse('index'))
        else:
            print(frm.errors)
    else:
        frm = LoginForm()
    con = {'frm': frm}
    return render(request, 'user/login.html', con)


def reg(request):
    if request.method == 'POST':
        form = RegForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Сәтті тіркелдіңіз!')
            return HttpResponseRedirect(reverse('user:log'))
        else:
            print(form.errors)
    else:
        form = RegForm()
    con = {'form': form}
    return render(request, 'user/register.html', con)


@login_required
def prof(request):
    user = request.user
    if request.method == 'POST':
        frm = ProfileForm(data=request.POST, files=request.FILES, instance=user)
        if frm.is_valid():
            frm.save()
            return HttpResponseRedirect(reverse('user:prof'))
    else:
        frm = ProfileForm(instance=user)
    baskets = Basket.objects.filter(user=user)
    total_quant = 0
    total_sum = 0
    for basket in baskets:
        total_quant += basket.quant
        total_sum += basket.sum()
    con = {'frm': frm, 'title': 'ХҚТУ - Жеке Кабинет',
           'baskets': baskets,
           'total_quantity': total_quant,
           'total_sum': total_sum,
           }
    return render(request, 'user/profile.html', con)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

user/templates/user/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>ХҚТУ  - Авторизация</title>
    <link href="{% static 'css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or frm.errors %}
                        <div class="alert  {% if messages  %} alert-success {% else %}  alert-warning {% endif %} alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% else  %}
                                {{ frm.non_field_errors}}
                            {% endif %}
{#                            <strong>Бірдеме дұрыс емес!</strong> Толтыру керек қатарларды тағы бір тексеріңіз.#}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'user:log' %}" method="post">
                                    {% csrf_token %}
{#                                    {{ frm.as_p }}#}
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ frm.username.id_for_label }}">Пайдаланушы аты</label>
                                        {{ frm.username }}
{#                                        <input class="form-control py-4" id="inputEmailAddress" type="email"#}
{#                                               placeholder="Пайдаланушы атын енгізіңіз"/>#}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ frm.password.id_for_label }}">Құпиясөз</label>
                                         {{ frm.password }}
{#                                        <input class="form-control py-4" id="inputPassword" type="password"#}
{#                                               placeholder="Құпиясөзді енгізіңіз"/>#}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Құпиясөз есіңізде емес пе?</a>
                                        <input class="btn btn-primary" type="submit" value="Кіру">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'user:reg' %}">Жаңа аккаунт қажет пе? Тіркел!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth.js' %}"></script>
</body>
</html>

user/templates/user/profile.html
{% extends 'product/baza.html' %}
{% load staticfiles %}

{% block css %}
    <link href="{% static 'css/profile.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}x
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="{% if user.img %} {{ user.img.url }} {% else %} {% static 'vendor/img/user/default.png' %}{% endif %}"
                         class="img-thumbnail">
                </div>
                <form action="{% url 'user:prof' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{frm.first_name.id_for_label}}">Атыңыз</label>
                                {{ frm.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{frm.last_name.id_for_label}}">Фамилияңыз</label>
                                {{ frm.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ frm.img }}
                                <label class="custom-file-label" for="{{ frm.img.id_for_label }}">Аватарка таңдаңыз/ауыстырыңыз</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
{#                        {% if %} {% endif %}#}
{#                        {% block %} {% endblock #}
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{frm.username.id_for_label}}">Пайдаланушы аты</label>
                            {{ frm.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{frm.email.id_for_label}}">Электрондық почта адресі</label>
                            {{ frm.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
            {% include 'product/basket.html' %}
        </div>
    </div>
{% endblock %}

user/templates/user/register.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Регистрация</title>
    <link href="{% static 'css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors%}
                             <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
{#                            <strong>Бірдеме дұрыс емес!</strong> Толтыру керек қатарларды тағы бір тексеріңіз.#}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
{#                        <div class="alert alert-warning alert-dismissible fade show" role="alert"#}
{#                             style="margin-top: 50px;">#}
{#                            {{ form.errors }}#}
{#                            <strong>Бірдеме дұрыс емес!</strong> Толтыру керек қатарларды тағы бір тексеріңіз.#}
{#                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">#}
{#                                <span aria-hidden="true">&times;</span>#}
{#                            </button>#}
{#                        </div>#}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Тіркелу</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'user:reg' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Аты</label>
                                                {{ form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Пайдаланушы аты</label>
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Электрондық почта адресі</label>
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Құпиясөз</label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Құпиясөзді тағы
                                                    еңгізіңіз</label>
                                                {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Аккаунт ашу">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'user:log' %}">Тіркелгенсіз бе? Авторизациядан
                                    өтіңіз</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth.js' %}"></script>
</body>
</html>