IKTU_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from product.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('product/', include('product.urls', namespace='product')),
    path('user/', include('user.urls', namespace='user')),
    path('basketadd/<int:product_id>/', include('product.urls', namespace='basketadd')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from product.views import product, baskett, basketDel

app_name = 'product'

urlpatterns = [
    path('', product, name='index'),
    path('baskett/<int:product_id>/', baskett, name='baskett'),
    path('bake/<int:id>/', basketDel, name='basketDel'),
]

user/urls.py
from django.urls import path

from user.views import log, reg, prof

app_name = 'user'

urlpatterns = [
    path('login/', log, name='log'),
    path('reg/', reg, name='reg'),
    path('prof/', prof, name='prof'),

]

product/models.py
from django.db import models
from user.models import User

# Create your models here.
class KorCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    descr = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Product Category'

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=256)
    img = models.ImageField(upload_to='products_images', blank=True)
    descr = models.TextField(blank=True)
    short_descr = models.CharField(max_length=64, blank=True)
    pr = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quant = models.PositiveIntegerField(default=0)
    categ = models.ForeignKey(KorCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} | {self.categ.name}'


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quant = models.PositiveIntegerField(default=0)
    created_timest = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Себет: {self.user.username} | Товар {self.product.name}'

    def sum(self):
        return self.quant * self.product.pr

product/views.py
from django.shortcuts import render, HttpResponseRedirect

from product.models import KorCategory, Products, Basket


def index(request):
    con = {
        'title': 'ХҚТУ сатылым қоры'
    }
    return render(request, 'product/index.html', con)


def product(request):
    con = {
        'title': 'Қор каталогы',
        'categories': KorCategory.objects.all(),
        'products': Products.objects.all()
    }
    return render(request, 'product/product.html', con)


def baskett(request, product_id):
    curPage = request.META.get('HTTP_REFERER')
    product = Products.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quant=1)
        return HttpResponseRedirect(curPage)
    else:
        basket = baskets.first()
        basket.quant += 1
        basket.save()
        return HttpResponseRedirect(curPage)

        # basket = Basket(user=request.user, product=product, quant=1)
        # basket.save()


def basketDel(request, id):
    basket = Basket.objects.get(id=id)
    basket.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

product/templates/product/basket.html
{% if baskets %}
    <div class="col-lg-5">
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Себет <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
        </h4>
        {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.short_descr }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">
                        <span class="text-muted">{{ basket.quant }} дана</span>
                        <span class="text-muted">{{ basket.sum }} тг.</span>
                        <span class="text-muted">
                            <a href="{% url 'product:baskett' basket.product.id%}" style="text-decoration: none; color: gray;">
                                <i class="fas fa-cart-plus"></i>
                            </a>
                            <a href="{% url 'product:basketDel' basket.id %}" style="text-decoration: none; color: gray;">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Барлығы</p>
                <h4 class="float-right">{{ total_sum }} тг.</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right">Рәсімдеу</button>
    </div>
{% else %}
     <h4 class="mt-3 mb-3 mb-3  text-center">
            Себетте әзірге ештеңе жоқ...
     </h4>
{% endif %}

product/templates/product/baza.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'product:index' %}">ХҚТУ сатылым қоры</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class >
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'product:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:log' %}">Кіру <i class="fas fa-sign-in-alt"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:prof' %}">Профиль
                        <i class="fas fa-user-circle"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:log' %}">Шығу <i class="fas fa-sign-out-alt"></i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block ff %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

product/templates/product/index.html
{% extends 'product/baza.html' %}
{% load staticfiles %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">ХҚТУ сатылым қоры</h1>
                    <p>
                        Жаңа стиль және де арзан бағалар! Бұл тек ХҚТУ универ қорында!<br>
                        Жаңа науқандарды байқап, өзіңді әдемі мерчтермен қуант!
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'product:index' %}">
                            Сатып алу
                        </a>
                    </button>
                </div>
            </div>
        </div>
</section>
{% endblock %}

product/templates/product/product.html
{% extends 'product/baza.html' %}
{% load staticfiles %}

{% block css %}
    <link href="{% static 'css/product.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">Мәзір</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="#" class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/yassawi-1.jpg" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/yassawi-2.jpg" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/yassawi-3.jpg" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Алдыңғы бет</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Келесі бет</span>
                    </a>
                </div>
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top"
                                     src="/media/{{ product.img }}"
                                     alt="">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#">{{ product.name }}</a>
                                </h4>
                                <h5>{{ product.pr }} тг.</h5>
                                <p class="card-text">{{ product.short_descr }}</p>
                            </div>
                            <div class="card-footer text-center">
                                <a href="{% url 'product:baskett' product.id%}">
                                    <button type="button" class="btn btn-outline-success">
                                        Жәшікке салу
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Алдыңғы бет
                            </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#">Келесі бет</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

{% block ff %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Арнайы ХҚТУ үшін 2022</p>
        </div>
    </footer>
{% endblock %}